import Influencer from "./types/influencer";

const DEFAULT_INFLUENCERS: Column[] = [
	{
		color: "yellow",
		heading: "Prospects",
		influencers: [
			{
				name: "Its me Gozde",
				username: "its_me_gozde",
				followerCount: 7500,
				platform: "Instagram",
				estimatedPromotionPrice: 100,
				image: "https://randomuser.me/api/portraits/men/1.jpg",
				profileLink: "https://instagram.com/its_me_gozde",
			},
			{
				name: "Football World",
				username: "football_world.2020",
				followerCount: 2500,
				platform: "Instagram",
				estimatedPromotionPrice: 100,
				image: "https://randomuser.me/api/portraits/men/2.jpg",
				profileLink: "https://instagram.com/football_world.2020",
			},
			{
				name: "Proud Leo Messi Fans",
				username: "proud_leo_messi_fans",
				followerCount: 2700,
				platform: "Instagram",
				estimatedPromotionPrice: 100,
				image: "https://randomuser.me/api/portraits/men/3.jpg",
				profileLink: "https://instagram.com/proud_leo_messi_fans",
			},
			{
				name: "N/A",
				username: "thiagomateomessi",
				followerCount: 12200,
				platform: "Instagram",
				estimatedPromotionPrice: 100,
				image: "https://randomuser.me/api/portraits/men/4.jpg",
				profileLink: "https://instagram.com/thiagomateomessi",
			},
			{
				name: "Love2clean",
				username: "homelifewithsage",
				followerCount: 13900,
				platform: "Instagram",
				estimatedPromotionPrice: 17781.56,
				image: "https://randomuser.me/api/portraits/men/5.jpg",
				profileLink: "https://instagram.com/homelifewithsage",
			},
			{
				name: "Love2clean",
				username: "homelifewithsage",
				followerCount: 13900,
				platform: "Instagram",
				estimatedPromotionPrice: 17781.56,
				image: "https://randomuser.me/api/portraits/men/6.jpg",
				profileLink: "https://instagram.com/homelifewithsage",
			},
			{
				name: "Travel With Tia",
				username: "travel_with_tia",
				followerCount: 9800,
				platform: "Instagram",
				estimatedPromotionPrice: 300,
				image: "https://randomuser.me/api/portraits/women/1.jpg",
				profileLink: "https://instagram.com/travel_with_tia",
			},
			{
				name: "Tech Guru",
				username: "tech_guru",
				followerCount: 42000,
				platform: "Instagram",
				estimatedPromotionPrice: 1500,
				image: "https://randomuser.me/api/portraits/men/2.jpg",
				profileLink: "https://instagram.com/tech_guru",
			},
			{
				name: "Fitness Fanatic",
				username: "fitness_fanatic",
				followerCount: 5600,
				platform: "Instagram",
				estimatedPromotionPrice: 200,
				image: "https://randomuser.me/api/portraits/women/2.jpg",
				profileLink: "https://instagram.com/fitness_fanatic",
			},
			{
				name: "Gourmet Guru",
				username: "gourmet_guru",
				followerCount: 12500,
				platform: "Instagram",
				estimatedPromotionPrice: 400,
				image: "https://randomuser.me/api/portraits/men/3.jpg",
				profileLink: "https://instagram.com/gourmet_guru",
			},
		],
	},
	{
		color: "pink",
		heading: "Reached out",
		influencers: [
			{
				name: "Lol",
				username: "curly__girllove",
				followerCount: 5300,
				platform: "Instagram",
				estimatedPromotionPrice: 100,
				image: "https://randomuser.me/api/portraits/men/7.jpg",
				profileLink: "https://instagram.com/curly__girllove",
			},
			{
				name: "Emil",
				username: "bulgariandaddy",
				followerCount: 59500,
				platform: "TikTok",
				estimatedPromotionPrice: 1612.47,
				image: "https://randomuser.me/api/portraits/men/8.jpg",
				profileLink: "https://www.tiktok.com/@bulgariandaddy",
			},
			{
				name: "Shweta Juyal",
				username: "makeupstoriesbyshweta",
				followerCount: 1300,
				platform: "Instagram",
				estimatedPromotionPrice: 100,
				image: "https://randomuser.me/api/portraits/men/9.jpg",
				profileLink: "https://instagram.com/makeupstoriesbyshweta",
				notifications: 8,
			},
			{
				name: "Tinku Kotadiya",
				username: "fairy_bridal_beauty",
				followerCount: 32800,
				platform: "Instagram",
				estimatedPromotionPrice: 574,
				image: "https://randomuser.me/api/portraits/men/10.jpg",
				profileLink: "https://instagram.com/fairy_bridal_beauty",
			},
			{
				name: "La casa de papel - Bella Ciao",
				username: "lacasadepapel",
				followerCount: 10700000,
				platform: "Instagram",
				estimatedPromotionPrice: 25000,
				image: "https://randomuser.me/api/portraits/men/11.jpg",
				profileLink: "https://instagram.com/lacasadepapel",
			},
			{
				name: "Healthy Eating",
				username: "healthy_eating",
				followerCount: 6700,
				platform: "Instagram",
				estimatedPromotionPrice: 300,
				image: "https://randomuser.me/api/portraits/women/3.jpg",
				profileLink: "https://instagram.com/healthy_eating",
			},
			{
				name: "Fashion Forward",
				username: "fashion_forward",
				followerCount: 12000,
				platform: "Instagram",
				estimatedPromotionPrice: 800,
				image: "https://randomuser.me/api/portraits/women/4.jpg",
				profileLink: "https://instagram.com/fashion_forward",
			},
			{
				name: "Music Mania",
				username: "music_mania",
				followerCount: 9000,
				platform: "Instagram",
				estimatedPromotionPrice: 500,
				image: "https://randomuser.me/api/portraits/men/4.jpg",
				profileLink: "https://instagram.com/music_mania",
			},
			{
				name: "Adventure Awaits",
				username: "adventure_awaits",
				followerCount: 7200,
				platform: "Instagram",
				estimatedPromotionPrice: 250,
				image: "https://randomuser.me/api/portraits/women/5.jpg",
				profileLink: "https://instagram.com/adventure_awaits",
			},
			{
				name: "Lol",
				username: "curly__girllove",
				followerCount: 5300,
				platform: "Instagram",
				estimatedPromotionPrice: 100,
				image: "https://randomuser.me/api/portraits/men/7.jpg",
				profileLink: "https://instagram.com/curly__girllove",
			},
		],
	},
	{
		color: "gray",
		heading: "In Conversation",
		influencers: [
			{
				name: "La casa de papel",
				username: "lacasadepapel",
				followerCount: 10700000,
				platform: "Instagram",
				estimatedPromotionPrice: 25000,
				image: "https://randomuser.me/api/portraits/men/12.jpg",
				profileLink: "https://instagram.com/lacasadepapel",
				notifications: 4,
			},
			{
				name: "Ali Abdaal",
				username: "aliabdaal",
				followerCount: 3500000,
				platform: "YouTube",
				estimatedPromotionPrice: 19320.09,
				image: "https://randomuser.me/api/portraits/men/13.jpg",
				profileLink: "https://www.youtube.com/user/aliabdaal",
				notifications: 2,
			},
			{
				name: "Rupinder Kaur",
				username: "simplyyroop",
				followerCount: 175600,
				platform: "Instagram",
				estimatedPromotionPrice: 3292.25,
				image: "https://randomuser.me/api/portraits/men/14.jpg",
				profileLink: "https://instagram.com/simplyyroop",
			},
			{
				name: "Tanish Garg",
				username: "fun.programmer",
				followerCount: 88400,
				platform: "Instagram",
				estimatedPromotionPrice: 100,
				image: "https://randomuser.me/api/portraits/men/15.jpg",
				profileLink: "https://instagram.com/fun.programmer",
			},
			{
				name: "N/A",
				username: "calorie_crush",
				followerCount: 2400,
				platform: "Instagram",
				estimatedPromotionPrice: 100,
				image: "https://randomuser.me/api/portraits/men/16.jpg",
				profileLink: "https://instagram.com/calorie_crush",
			},
			{
				name: "Tech Trends",
				username: "tech_trends",
				followerCount: 650000,
				platform: "YouTube",
				estimatedPromotionPrice: 12000,
				image: "https://randomuser.me/api/portraits/men/6.jpg",
				profileLink: "https://www.youtube.com/tech_trends",
			},
			{
				name: "Travel Diaries",
				username: "travel_diaries",
				followerCount: 200000,
				platform: "YouTube",
				estimatedPromotionPrice: 8000,
				image: "https://randomuser.me/api/portraits/women/6.jpg",
				profileLink: "https://www.youtube.com/travel_diaries",
			},
			{
				name: "Home Hacks",
				username: "home_hacks",
				followerCount: 150000,
				platform: "YouTube",
				estimatedPromotionPrice: 7000,
				image: "https://randomuser.me/api/portraits/men/7.jpg",
				profileLink: "https://www.youtube.com/home_hacks",
			},
			{
				name: "Gaming Legends",
				username: "gaming_legends",
				followerCount: 90000,
				platform: "YouTube",
				estimatedPromotionPrice: 5000,
				image: "https://randomuser.me/api/portraits/men/8.jpg",
				profileLink: "https://www.youtube.com/gaming_legends",
			},
			{
				name: "La casa de papel",
				username: "lacasadepapel",
				followerCount: 10700000,
				platform: "Instagram",
				estimatedPromotionPrice: 25000,
				image: "https://randomuser.me/api/portraits/men/12.jpg",
				profileLink: "https://instagram.com/lacasadepapel",
			},
		],
	},
	{
		color: "green",
		heading: "Onboarded",
		influencers: [
			{
				name: "Ram Pandey",
				username: "sleepshopbc",
				followerCount: 5100,
				platform: "Instagram",
				estimatedPromotionPrice: 100,
				image: "https://randomuser.me/api/portraits/men/17.jpg",
				profileLink: "https://instagram.com/sleepshopbc",
			},
			{
				name: "Beauty Bliss",
				username: "beauty_bliss",
				followerCount: 4300,
				platform: "Instagram",
				estimatedPromotionPrice: 150,
				image: "https://randomuser.me/api/portraits/women/7.jpg",
				profileLink: "https://instagram.com/beauty_bliss",
			},
			{
				name: "Fitness Fusion",
				username: "fitness_fusion",
				followerCount: 8200,
				platform: "Instagram",
				estimatedPromotionPrice: 300,
				image: "https://randomuser.me/api/portraits/men/8.jpg",
				profileLink: "https://instagram.com/fitness_fusion",
			},
			{
				name: "Pet Lover",
				username: "pet_lover",
				followerCount: 3500,
				platform: "Instagram",
				estimatedPromotionPrice: 120,
				image: "https://randomuser.me/api/portraits/women/8.jpg",
				profileLink: "https://instagram.com/pet_lover",
			},
			{
				name: "Foodie Finds",
				username: "foodie_finds",
				followerCount: 7100,
				platform: "Instagram",
				estimatedPromotionPrice: 250,
				image: "https://randomuser.me/api/portraits/men/9.jpg",
				profileLink: "https://instagram.com/foodie_finds",
			},
			{
				name: "Ram Pandey",
				username: "sleepshopbc",
				followerCount: 5100,
				platform: "Instagram",
				estimatedPromotionPrice: 100,
				image: "https://randomuser.me/api/portraits/men/17.jpg",
				profileLink: "https://instagram.com/sleepshopbc",
			},

			{
				name: "N/A",
				username: "blendandchat",
				followerCount: 46,
				platform: "Instagram",
				estimatedPromotionPrice: 100,
				image: "https://randomuser.me/api/portraits/men/18.jpg",
				profileLink: "https://instagram.com/blendandchat",
			},
			{
				name: "Bio-Oil",
				username: "biooilaustralia",
				followerCount: 5400,
				platform: "Instagram",
				estimatedPromotionPrice: 100,
				image: "https://randomuser.me/api/portraits/men/19.jpg",
				profileLink: "https://instagram.com/biooilaustralia",
			},
			{
				name: "Assim Abbasi",
				username: "itz_bittu_8886",
				followerCount: 2500,
				platform: "Instagram",
				estimatedPromotionPrice: 100,
				image: "https://randomuser.me/api/portraits/men/20.jpg",
				profileLink: "https://instagram.com/itz_bittu_8886",
			},
		],
	},
	{
		color: "red",
		heading: "Rejected",
		influencers: [
			{
				name: "Christmas Aye🎄🎅",
				username: "bbwria",
				followerCount: 1700,
				platform: "Instagram",
				estimatedPromotionPrice: 100,
				image: "https://randomuser.me/api/portraits/men/21.jpg",
				profileLink: "https://instagram.com/bbwria",
			},
			{
				name: "Kunal Kamra",
				username: "kunal_kamra",
				followerCount: 1000000,
				platform: "Instagram",
				estimatedPromotionPrice: 5689.41,
				image: "https://randomuser.me/api/portraits/men/22.jpg",
				profileLink: "https://instagram.com/kunal_kamra",
			},
			{
				name: "Maddy",
				username: "allthings.fragrance",
				followerCount: 6600,
				platform: "Instagram",
				estimatedPromotionPrice: 100,
				image: "https://randomuser.me/api/portraits/men/23.jpg",
				profileLink: "https://instagram.com/allthings.fragrance",
			},
			{
				name: "Comedy Central",
				username: "comedy_central",
				followerCount: 2500,
				platform: "Instagram",
				estimatedPromotionPrice: 150,
				image: "https://randomuser.me/api/portraits/men/24.jpg",
				profileLink: "https://instagram.com/comedy_central",
			},
			{
				name: "Health Tips",
				username: "health_tips",
				followerCount: 4000,
				platform: "Instagram",
				estimatedPromotionPrice: 200,
				image: "https://randomuser.me/api/portraits/women/9.jpg",
				profileLink: "https://instagram.com/health_tips",
			},
		],
	},
];

export { DEFAULT_INFLUENCERS };

type Column = {
	color: string;
	heading: string;
	influencers: Influencer[];
};
